.TH "libstdf.h" 3 "24 Mar 2017" "libstdf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libstdf.h \- 
.SH "Detailed Description"
.PP 
Top level include and the main stdf structure definition. 


.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void \fBstdf_file\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBstdf_format\fP { \fBSTDF_FORMAT_REG\fP =  0x0, \fBSTDF_FORMAT_ZIP\fP =  0x1, \fBSTDF_FORMAT_GZIP\fP =  0x2, \fBSTDF_FORMAT_BZIP2\fP =  0x3, \fBSTDF_FORMAT_LZW\fP =  0x4 }"
.br
.ti -1c
.RI "enum \fBstdf_initial_options\fP { \fBSTDF_OPTS_DEFAULT\fP =  0x000, \fBSTDF_OPTS_FORCE\fP =  0x001, \fBSTDF_OPTS_FORCE_V3\fP =  0x002, \fBSTDF_OPTS_FORCE_V4\fP =  0x004, \fBSTDF_OPTS_ZIP\fP =  0x008, \fBSTDF_OPTS_GZIP\fP =  0x010, \fBSTDF_OPTS_BZIP2\fP =  0x020, \fBSTDF_OPTS_LZW\fP =  0x040, \fBSTDF_OPTS_READ\fP =  0x080, \fBSTDF_OPTS_WRITE\fP =  0x100, \fBSTDF_OPTS_CREATE\fP =  0x200 }"
.br
.ti -1c
.RI "enum \fBstdf_runtime_settings\fP { \fBSTDF_SETTING_WRITE_SIZE\fP =  0x001, \fBSTDF_SETTING_VERSION\fP =  0x002, \fBSTDF_SETTING_BYTE_ORDER\fP =  0x003 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBstdf_format\fP"
.PP
Compressed file format 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISTDF_FORMAT_REG \fP\fP
Regular file 
.TP
\fB\fISTDF_FORMAT_ZIP \fP\fP
Zipped file 
.TP
\fB\fISTDF_FORMAT_GZIP \fP\fP
gzipped file 
.TP
\fB\fISTDF_FORMAT_BZIP2 \fP\fP
bzipped file 
.TP
\fB\fISTDF_FORMAT_LZW \fP\fP
LZW compressed file 
.SS "enum \fBstdf_initial_options\fP"
.PP
Misc options to control libstdf behavior 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISTDF_OPTS_DEFAULT \fP\fP
Default options 
.TP
\fB\fISTDF_OPTS_FORCE \fP\fP
Force reading even if some sanity checks fail 
.TP
\fB\fISTDF_OPTS_FORCE_V3 \fP\fP
Force STDFv3 behavior 
.TP
\fB\fISTDF_OPTS_FORCE_V4 \fP\fP
Force STDFv4 behavior 
.TP
\fB\fISTDF_OPTS_ZIP \fP\fP
File is compressed with zip 
.TP
\fB\fISTDF_OPTS_GZIP \fP\fP
File is compressed with gzip 
.TP
\fB\fISTDF_OPTS_BZIP2 \fP\fP
File is compressed with bzip2 
.TP
\fB\fISTDF_OPTS_LZW \fP\fP
File is compressed with lzw 
.TP
\fB\fISTDF_OPTS_READ \fP\fP
Allow reading from file 
.TP
\fB\fISTDF_OPTS_WRITE \fP\fP
Allow writing to file 
.TP
\fB\fISTDF_OPTS_CREATE \fP\fP
Create file from scratch 
.SS "enum \fBstdf_runtime_settings\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fISTDF_SETTING_WRITE_SIZE \fP\fP
Set the output blocksize for writing 
.TP
\fB\fISTDF_SETTING_VERSION \fP\fP
Query the STDF spec version 
.TP
\fB\fISTDF_SETTING_BYTE_ORDER \fP\fP
Query the byte order 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdf from the source code.
